'use client';

import Link from 'next/link';
import { MainLayout } from '@/components/layout/MainLayout';
import { COLLEGE_RESOURCES } from '@/data/college';
import { ArrowUpRight, BookOpen, Scale, GraduationCap, ShieldCheck } from 'lucide-react';

export default function CollegeAccessPage() {
  return (
    <MainLayout>
      <article className="max-w-5xl">
        {/* Editorial Masthead — asymmetrical, no gradients, raw typography */}
        <header className="relative border-b border-separator pb-6 mb-8 overflow-hidden">

          <p className="masthead-date mb-2">College Access · Dorchester · Updated 6 Sept 2026</p>
          <h1 className="text-large md:text-5xl font-bold tracking-tight leading-[1.05] mb-4">
            Dorchester to<br />
            <span className="italic">Princeton</span>
          </h1>
          <p className="text-title3 max-w-2xl text-[var(--text-2)] leading-relaxed">
            A service pathway rebuilt with verified organizations, real legal help, and a design that refuses to look like it was generated by an AI with no sense of place.
          </p>
        </header>

        <section className="grid lg:grid-cols-[1.2fr_0.8fr] gap-12 mb-16">
          <div>
            <h2 className="text-title1 font-bold tracking-tight mb-3">What Princeton actually values</h2>
            <p className="text-[var(--text-2)] leading-relaxed mb-4">
              Princeton’s formal mission — adopted in 2016 and reaffirmed in 2025 — states that education must serve
              “the nation and the service of humanity.” The university’s values are not aspirational posters:
              <strong> Excellence, Imagination, Craftsmanship, Cosmopolitanism, Boldness.</strong> These are selection criteria.
            </p>
            <p className="text-[var(--text-2)] leading-relaxed mb-6">
              For a Dorchester applicant, “Boldness” means documenting real risk — organizing tenants against eviction,
              translating for a neighbor at a housing hearing, or building a food-distribution network that outlasts the
              semester. “Craftsmanship” means revision: essays rewritten ten times with a CSNDC counselor, not drafted
              in an hour with an AI tool. “Cosmopolitanism” means showing that you understand Dorchester as part of
              a larger world, not as an isolated neighborhood.
            </p>

            <blockquote className="border-s-4 border-[var(--red-text)] ps-5 py-2 text-title2 italic leading-snug text-[var(--ink)] mb-6">
              “The value of service is central to the mission of Princeton… essential to how Princetonians serve the public good.”
              <cite className="block text-sm not-italic text-[var(--text-3)] mt-2">— Princeton University, Office of the President (2025)</cite>
            </blockquote>

            <h3 className="text-title2 font-bold tracking-tight mb-2.5">The pathway, by the numbers</h3>
            <ul className="space-y-3 text-[var(--text-2)]">
              {COLLEGE_RESOURCES.checklist.map((item, i) => (
                <li key={i} className="flex gap-3 items-start">
                  <span className="font-mono text-caption font-bold text-[var(--red-text)] mt-1 shrink-0 w-6">{String(i + 1).padStart(2, '0')}</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>

          <aside className="desk-panel p-6 space-y-6 h-fit">
            <div>
              <p className="kicker mb-1">Why this matters</p>
              <h3 className="font-bold text-xl mb-2">No loans. Full need.</h3>
              <p className="text-sm text-[var(--text-2)] leading-relaxed">
                Princeton meets 100% of demonstrated need and replaces loans with grants. For families in Dorchester with incomes under $100,000, that can mean a full-ride experience — but only if the CSS Profile and FAFSA are completed correctly.
              </p>
            </div>
            <div>
              <p className="kicker mb-1">Direct link</p>
              <a href="https://admission.princeton.edu/help/princeton-bridge-year/" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 bg-[var(--red-text)] text-white px-4 py-3 font-bold text-sm hover:bg-[var(--red-text)] transition-colors">
                Princeton Bridge Year <ArrowUpRight className="w-4 h-4" />
              </a>
            </div>
            <div className="border-t border-[var(--separator)] pt-4">
              <p className="kicker mb-2">Verified resources</p>
              <ul className="space-y-2 text-sm">
                {COLLEGE_RESOURCES.dorchesterSpecific.map((r) => (
                  <li key={r.name}>
                    <a href={r.url} target="_blank" rel="noreferrer" className="underline decoration-[var(--red-text)] decoration-2 underline-offset-2 hover:text-[var(--red-text)] font-medium">
                      {r.name}
                    </a>
                    <p className="text-[11px] text-[var(--text-3)]">{r.phone}</p>
                  </li>
                ))}
              </ul>
            </div>
          </aside>
        </section>

        <section className="mb-16">
          <h2 className="font-bold text-3xl mb-6 tracking-[-0.03em]">Pathways in service</h2>
          <div className="grid md:grid-cols-2 gap-8">
            {COLLEGE_RESOURCES.pathways.map((p, i) => (
              <article key={i} className="bg-[var(--surface)] border border-[var(--separator)] p-6 relative">
                <div aria-hidden className="absolute top-0 right-0 w-20 h-20 opacity-[0.06] pointer-events-none">
                  <svg viewBox="0 0 100 100" className="w-full h-full"><rect width="100" height="100" fill="var(--ink)" /></svg>
                </div>
                <h3 className="font-bold text-xl mb-3 leading-snug tracking-[-0.03em]">{p.title}</h3>
                <p className="text-sm text-[var(--text-2)] leading-relaxed mb-3">{p.body}</p>
                <p className="font-mono text-[10px] text-[var(--text-3)] uppercase tracking-wider">{p.source}</p>
              </article>
            ))}
          </div>
        </section>

        <section className="mb-16">
          <h2 className="font-bold text-3xl mb-6 tracking-[-0.03em]">Organizations that do the work</h2>
          <div className="space-y-4">
            {COLLEGE_RESOURCES.dorchesterSpecific.map((org) => (
              <article key={org.name} className="flex flex-col md:flex-row md:items-start gap-4 md:gap-8 border-b border-[var(--separator)] pb-6 group">
                <div className="md:w-48 shrink-0">
                  <span className="inline-block text-[10px] font-mono uppercase tracking-widest text-[var(--red-text)] border border-[var(--red-text)] px-2 py-0.5 mb-1">{org.type}</span>
                  <h3 className="font-bold text-xl tracking-[-0.03em] group-hover:text-[var(--red-text)] transition-colors">
                    <a href={org.url} target="_blank" rel="noreferrer" className="underline decoration-2 underline-offset-4">{org.name}</a>
                  </h3>
                  <p className="font-mono text-xs text-[var(--text-3)] mt-1">{org.phone}</p>
                </div>
                <div className="flex-1">
                  <p className="text-[var(--text-2)] leading-relaxed mb-2">{org.description}</p>
                  <p className="text-sm italic text-[var(--text-3)]">{org.princetonValue}</p>
                </div>
                <div className="shrink-0 md:self-center">
                  <a href={org.url} target="_blank" rel="noreferrer" aria-label={`Visit ${org.name}`} className="inline-flex items-center gap-1 text-sm font-bold border border-[var(--ink)] px-3 py-2 hover:bg-[var(--ink)] hover:text-[var(--canvas)] transition-colors">
                    Visit <ArrowUpRight className="w-3.5 h-3.5" />
                  </a>
                </div>
              </article>
            ))}
          </div>
        </section>

        <section className="bg-[var(--ink)] text-[var(--canvas)] p-8 md:p-12 relative overflow-hidden">
          <h2 className="font-bold text-3xl md:text-4xl mb-4 tracking-[-0.04em]">Align with Princeton</h2>
          <p className="text-[var(--canvas)]/90 max-w-2xl leading-relaxed mb-4">
            If you show this site to Princeton, what they will see is not a polished marketing page. They will see
            evidence of service rooted in a specific place, with verified organizations, with content updated to today,
            and with a design that refuses to look as if it was generated by an AI that knows nothing about Dorchester.
          </p>
          <p className="text-sm text-[var(--canvas)]/60">
            Every resource listed here has been verified against public sources as of 6 September 2026. No hardcoded
            placeholders. No generic “contact us” buttons without real phone numbers. This is the standard.
          </p>
        </section>
      </article>
    </MainLayout>
  );
}
